image:
  repository: everpeace/kube-openmpi
  tag: 0.4.0
  pullPolicy: IfNotPresent

kubectlImage:
  repository: everpeace/kubectl
  tag: 1.9.2
  pullPolicy: IfNotPresent

gitSyncImage:
  repository: gcr.io/google_containers/git-sync
  tag: v2.0.6
  pullPolicy: IfNotPresent

networkPolicy:
  enabled: false

sshGateway:
  enabled: false
  nodePort: 30220

sshKey:
  # id_rsa: |
  #   ...
  # id_rsa_pub: |
  #   ...

mpiMaster:
  autoUpdateHostfile:
    enabled: true
    updateEvery: 15
  # command: |
  #   mpiexec --hostfile /mpi-cluster/hostfile \
  #     --display-map -n 4 -npernode 1 \
  #     -- sh -c 'echo $(hostname):hello'
  securityContext:
  #   runAsUser: 1000
  #   fsGroup: 1000
  resources:
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

mpiWorkers:
  num: 4
  securityContext:
  #   runAsUser: 1000
  #   fsGroup: 1000
  resources:
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    #  gpu: 1
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
    #  gpu: 1
  podManagementPolicy: Parallel
  nodeSelector: {}
  tolerations: []
  affinity: {}

appCodesToSync:
# - name: chainermn
#   gitRepo: https://github.com/chainer/chainermn.git
#   gitBranch: master
#   fetchWaitSecond: "120"
#   mountPath: /chainermn-examples
#   subPath: chainermn/examples
# - name: chainer
#   gitRepo: https://github.com/chainer/chainer.git
#   gitBranch: master
#   fetchWaitSecond: "120"
#   mountPath: /chainer-examples
#   subPath: chainer/examples
