image:
  repository: everpeace/kube-openmpi
  tag: 0.5.1

networkPolicy:
  enabled: false

sshGateway:
  enabled: false
  nodePort: 30220

mpiMaster:
  autoUpdateHostfile:
    enabled: true
  # securityContext:
  #   runAsUser: 1000
  #   fsGroup: 1000
  resources:
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  # volumes:
  # - name: cache-volume
  #   emptyDir: {}
  # volumeMounts:
  # - mountPath: /cache
  #   name: cache-volume

mpiWorkers:
  num: 4
  # securityContext:
  #   runAsUser: 1000
  #   fsGroup: 1000
  resources:
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    #  gpu: 1
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
    #  gpu: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  # volumes:
  # - name: cache-volume
  #   emptyDir: {}
  # volumeMounts:
  # - mountPath: /cache
  #   name: cache-volume

appCodesToSync:
# - name: chainermn
#   gitRepo: https://github.com/chainer/chainermn.git
#   gitBranch: master
#   fetchWaitSecond: "120"
#   mountPath: /chainermn-examples
#   subPath: chainermn/examples
# - name: chainer
#   gitRepo: https://github.com/chainer/chainer.git
#   gitBranch: master
#   fetchWaitSecond: "120"
#   mountPath: /chainer-examples
#   subPath: chainer/examples
