image:
  repository: _EDIT_ME_
  tag: _EDIT_ME_

mpiMaster:
  autoUpdateHostfile:
    enabled: true
  # resources:
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  # securityContext:
  #   runAsUser: 1000
  #   fsGroup: 1000
  # volumes:
  # - name: cache-volume
  #   emptyDir: {}
  # volumeMounts:
  # - mountPath: /cache
  #   name: cache-volume

mpiWorkers:
  num: 2
  resources:
    limits:
      nvidia.com/gpu: 1
      # cpu: 100m
      # memory: 128Mi
  # securityContext:
  #   runAsUser: 1000
  #   fsGroup: 1000
  # volumes:
  # - name: cache-volume
  #   emptyDir: {}
  # volumeMounts:
  # - mountPath: /cache
  #   name: cache-volume
  
appCodesToSync:
- name: chainermn
  gitRepo: https://github.com/chainer/chainermn.git
  gitBranch: master
  fetchWaitSecond: "120"
  mountPath: /chainermn-examples
  subPath: chainermn/examples
