image:
  repository: _EDIT_ME_
  tag: _EDIT_ME_
  # pullPolicy: IfNotPresent
  # pullSecrets:
  # - name: ""

mpiMaster:
  autoUpdateHostfile:
    enabled: true
  oneShot:
    enabled: true
    # This will scale workers down to 0 when command completed successfully.
    autoScaleDownWorkers: true
    command: |
      mpiexec --allow-run-as-root \
        --hostfile /kube-openmpi/generated/hostfile \
        --display-map -n 2 -npernode 1 \
        python3 /chainermn-examples/mnist/train_mnist.py -g
  # resources:
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  # securityContext:
  #   runAsUser: 1000
  #   fsGroup: 1000
  # volumes:
  # - name: cache-volume
  #   emptyDir: {}
  # volumeMounts:
  # - mountPath: /cache
  #   name: cache-volume

mpiWorkers:
  num: 2
  resources:
    limits:
      nvidia.com/gpu: 1
      # cpu: 100m
      # memory: 128Mi
  # securityContext:
  #   runAsUser: 1000
  #   fsGroup: 1000
  # volumes:
  # - name: cache-volume
  #   emptyDir: {}
  # volumeMounts:
  # - mountPath: /cache
  #   name: cache-volume

appCodesToSync:
- name: chainermn
  gitRepo: https://github.com/chainer/chainermn.git
  gitBranch: master
  fetchWaitSecond: "120"
  mountPath: /chainermn-examples
  subPath: chainermn/examples
# - name: your-secret-repo
#   gitRepo: git@github.com:your-org/your-secret-repo.git
#   gitBranch: master
#   fetchWaitSecond: "120"
#   mountPath: /your-secret-repo
#   gitSecretName: git-sync-creds
